 version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
    angular-service: # The name of the service
      container_name: angular-container1  # Container name
      build: ./ # Location of our Dockerfile
      volumes: # Volume binding
        - './:/usr/src/app' 
      ports: 
        - '4200:80' # Port mapping
      command: > 
        bash -c "npm start"
