version: '3'

services:
  mysql-standalone1:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=foodboox
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin
  springboot-docker-container:
   image: springboot-docker-container
   ports:
     - 8082:8080
   build:
     context: ./
     dockerfile: Dockerfile
   depends_on:
     - mysql-standalone1       